image: FROM node:14.18.2-alpine3.14

stages:
    - test

before_script:
  - yarn install

CreateReportTests:
    stage: test
    script:
        - yarn test
    artifacts:
        when: always
        reports:
            junit: junit.xml

# CreateReportTestsCoverage:
#     stage: test
#     script:
#         - pytest --workers auto --tests-per-worker auto --cov-report xml:report_cov.xml --cov=lunespy/
#     artifacts:
#         when: always
#         reports:
#             junit: report_cov.xml
