image: node:14.18.2-alpine3.14

stages:
    - test

before_script:
  - yarn install

CreateReportTests:
    stage: test
    script:
        - yarn test
    artifacts:
        when: always
        reports:
            junit: junit.xml
