name: Deploy LunesJs on NPM

on:
    push:
        branches: [main]

jobs:
    fmt:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v3

          - name: Install dependencies
            run: yarn install -D

          - name: Format Checker
            run: yarn fmtc

    test:
      runs-on: ubuntu-latest
      needs: fmt

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3

        - name: Install dependencies
          run: yarn install -D

        - name: Format Checker
          run: yarn test

    deploy-npm:
        runs-on: ubuntu-latest
        needs: [fmt, test]

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: yarn install
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
