name: Deploy LunesJs on NPM

on:
    push:
        branches: [auto-deploy]

jobs:
  deploy-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install
      - run: yarn fmtc
      - run: yarn test

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}