name: Format Checker

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    format-checker:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: yarn install -D

            - name: Format Checker
              run: yarn fmtc
