name: Lint & Test

on:
    push:
        branches-ignore: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v3

          - name: Install dependencies
            run: yarn install -D

          - name: Format Checker
            run: yarn fmtc

    test:
      runs-on: ubuntu-latest
      needs: lint

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3

        - name: Install dependencies
          run: yarn install -D

        - name: Format Checker
          run: yarn test
