name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    unit-test:
        runs-on: ubuntu-latest
        # needs: format-checker

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: yarn install -D

            - name: Test with jest
              run: yarn test
